### ISSUE TITLE
Toumi

### ISSUE THREAD

**Issue by TouffeTouffe** [thomas40510/InfoMythe#1]
Hello, is this toumiaïed approved?
Thank you,
Fred

**Comment by thomas40510** [comment]
Excellent question, thanks for the heads up!
It is PEP8 compliant as it was developed under the "norme l'impro" and the "tkt ça fonctionne" paradigm. 
As everything else it is ISO 9001, 45001, 14105 and any convenient random number you can think of. 
Unfortunately, it is not sufficiently f'd up to have the Toumi-seal of approval.

**Comment by thomas40510** [comment]
Closed as not fundable with the current project-allocated resources.
